### ISSUE TITLE
Multiple instances do not keep in sync

### ISSUE THREAD

**Issue by desert** [adi518/vue-facebook-login-component#44]
![image](https://user-images.githubusercontent.com/723830/81489421-cd661800-923a-11ea-8838-ae969a4327e7.png)

**Comment by adi518** [comment]
I can fix it, but it'll take a little time.

**Comment by adi518** [comment]
Fixed it, but I think I rather release it after dealing with the previous issue.

**Comment by adi518** [comment]
Try new version `2.3.0`. Has a new prop and a fix for this issue.

**Comment by desert** [comment]
I think this is still not working, what should be done in order to keep them in sync?

**Comment by adi518** [comment]
You must share the same model between the instances.

**Comment by desert** [comment]
I just have two of these at different places of the same `<template>`:
```
 <v-facebook-login
                        app-id="228044118517087"
                        @login="onFbLogin"
                        @logout="onFbLogout"
                        @click="onFbClick"
                        @sdk-init="onFbSdkInit"
                        :login-options="{ scope: ['email'] }"
                      />
```

How do I share the model, which model?

**Comment by adi518** [comment]
You need to add `v-model` attribute to each instance.

**Comment by desert** [comment]
Okay, will do that.

**Comment by desert** [comment]
Excellent, it worked. Maybe add it to the docs.

**Comment by desert** [comment]
Right now those are in the same component. But what will happen if i need it in a nested component?

Shall I share it thru the Vuex `$store`?

**Comment by adi518** [comment]
Exactly, just the share the model from Vuex.
